<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 29.01.2017
 * Time: 2:29
 */

namespace app\controllers;


use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

class AjaxController extends Controller
{
    public function beforeAction($action)
    {
        \Yii::$app->session->set('languages',[0, 0, 0]);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
//        $this->view->registerJsFile("@web/js/script.js",
//            ["depends" => [\yii\web\JqueryAsset::className()]]);
        return $this->render("index", ["data"=>'', 'time' => new \DateTime]);
    }

    public function actionFormSubmission()
    {
        $lang = \Yii::$app->request->post('languages', '');
        return $this->render("index", ["data"=>$lang, 'time' => new \DateTime()]);
    }

    public function actionTime()
    {
        return $this->render('index', ["data"=>'', 'time' => new \DateTime()]);
    }

    public function actionGetData()
    {
        $city = \yii::$app->request->post('city', 'null');
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        return ['test','data', $city];
    }

    public function actionVote()
    {
        return $this->render('vote');
    }
}